using System.Collections.Generic;
using System.Linq;

namespace GildedFate.Core
{
    // Events Rework: one flavor line per classic option, shown in italics under the option title.
    // Kept apart from the definitions so balance edits never touch the writing.
    public static partial class EventContent
    {
        // Built on demand: a static field here could initialize after EventContent.All (field order across partial files is undefined).
        private static Dictionary<string,string> ClassicFlavorLines()=>new()
        {
            ["abandoned_forge/sharpen"]="The anvil still remembers the last edge it made.",
            ["abandoned_forge/reinforce"]="Heat the plate until it forgets how to bend.",
            ["abandoned_forge/ashes"]="Smiths always drop a few coins.",
            ["frayed_thread/pull"]="It cuts as it comes loose.",
            ["frayed_thread/armor"]="The strand tightens like a second skin.",
            ["frayed_thread/leave"]="A few gold beads fall when you step back.",
            ["heavy_blade/lift"]="Only a heavy strike can carry its weight.",
            ["heavy_blade/gold"]="The hilt is worth more than the blade.",
            ["stolen_second/moment"]="Pocket a second nobody will miss.",
            ["stolen_second/smash"]="Something bright spills from the gears.",
            ["traveling_merchant/card"]="He swears they're not stolen.",
            ["traveling_merchant/shard"]="Still warm. Don't ask why.",
            ["traveling_merchant/chest"]="He's looking the other way. Mostly.",
            ["empty_grave/dig"]="Whoever lies here won't need it.",
            ["empty_grave/offering"]="Leave something behind for the dead.",
            ["empty_grave/leave"]="Let the nameless rest.",
            ["bent_sword/blade"]="Bent, but it held long enough.",
            ["bent_sword/supplies"]="Bandages and a few coins.",
            ["bent_sword/bury"]="Bury your old habits with them.",
            ["three_sealed_doors/sword"]="The blade door opens onto a training hall.",
            ["three_sealed_doors/shield"]="The shield door opens onto an armory.",
            ["three_sealed_doors/eye"]="The eye door opens onto something watching back.",
            ["golden_beggar/gold"]="His hand closes slowly around the coins.",
            ["golden_beggar/card"]="He takes it like it weighs nothing.",
            ["golden_beggar/refuse"]="He lowers his hand without a word.",
            ["shardfall/careful"]="Pick the one that hums your name.",
            ["shardfall/all"]="The edges bite, but they're all yours.",
            ["shardfall/sell"]="Someone will pay well for a crater.",
            ["cracked_mirror/reach"]="Trade cards with the you on the other side.",
            ["cracked_mirror/break"]="The glass takes a card as it falls.",
            ["cracked_mirror/look"]="Your reflection deals from a stranger's deck.",
            ["hungry_chest/gold"]="It swallows, then spits something back.",
            ["hungry_chest/card"]="It chews slowly and pays for the meal.",
            ["hungry_chest/force"]="Pry its jaws open. Mind your fingers.",
            ["fallen_banner/carry"]="Old soldiers fought harder beneath it.",
            ["fallen_banner/gold"]="The thread is real gold.",
            ["fallen_banner/study"]="The markings are a battle plan.",
            ["forgotten_shrine/coin"]="The statue doesn't stop you.",
            ["forgotten_shrine/charm"]="It pricks your palm as you lift it.",
            ["forgotten_shrine/kneel"]="Rest, and the shrine rests with you.",
            ["wrong_road/safe"]="A quiet path and a little rest.",
            ["wrong_road/danger"]="Things in the trees drop what they carry.",
            ["wrong_road/gold"]="The footprints end at something bright.",
            ["binding_chamber/bind"]="Step into the orbit and let it choose.",
            ["living_ink/attack"]="The ink sharpens what it touches.",
            ["living_ink/skill"]="The ink settles in and holds fast.",
            ["living_ink/drink"]="It tastes like copper and prophecy.",
            ["hanging_chains/chain"]="One link binds a card to you for good.",
            ["hanging_chains/melt"]="Gold chains melt into gold coins.",
            ["golden_halo/accept"]="Let one card wear the light.",
            ["golden_halo/shatter"]="Holy glass cuts like any other.",
            ["focused_lens/focus"]="Everything it touches grows stronger.",
            ["focused_lens/sell"]="Collectors pay for curiosities.",
            ["echoing_library/own"]="Your best chapters, already written.",
            ["echoing_library/other"]="Borrow a stranger's technique.",
            ["echoing_library/burn"]="Burn two pages and keep the smoke.",
            ["locked_reliquary/pay"]="Some locks open for coin.",
            ["locked_reliquary/break"]="Some locks open for blood.",
            ["locked_reliquary/leave"]="It'll still be locked tomorrow.",
            ["collector_event/shard"]="He collects broken fates.",
            ["collector_event/relic"]="Trade a trinket for something rare.",
            ["collector_event/leave"]="He writes your name down anyway.",
            ["card_eater/one"]="A small meal settles it, and you.",
            ["card_eater/two"]="It eats well, then sits heavy in your deck.",
            ["card_eater/away"]="It drops what it was carrying.",
            ["broken_fatewheel/spin"]="Every spoke points somewhere different.",
            ["strangers_deck/choose"]="Learn a style you've never fought.",
            ["duel/honor"]="Fight fair and earn its respect.",
            ["duel/unfair"]="Win dirty and carry the shame.",
            ["duel/refuse"]="Walk away and catch your breath.",
            ["golden_surgeon/one"]="A clean cut for a fair price.",
            ["golden_surgeon/two"]="Two cuts, no anesthetic.",
            ["golden_surgeon/improve"]="Sharpen what's left. It hurts.",
            ["shard_smith/repair"]="He welds the crack shut.",
            ["shard_smith/trade"]="He swaps it before you can change your mind.",
            ["false_treasure_room/little"]="Take a handful and go.",
            ["false_treasure_room/lot"]="Greed has a way of following you.",
            ["false_treasure_room/chest"]="The seal breaks. So does something else.",
            ["recurring_knot/bind"]="A card that always comes back.",
            ["third_mark/bind"]="Every third time, fate pays out.",
            ["perfect_inscription/bind"]="Only a finished card can hold it.",
            ["master_binder/bind"]="The finest work, at the finest price.",
            ["severed_future/past"]="Cut away what you were.",
            ["severed_future/future"]="Lean into who you're becoming.",
            ["severed_future/refuse"]="Keep both, and pocket a shard.",
            ["crown_without_king/wear"]="It fits. That's the problem.",
            ["crown_without_king/sell"]="Dead kings fetch good prices.",
            ["crown_without_king/destroy"]="Break the crown and break a curse.",
            ["nameless_card/copy"]="Give it a name, and it gives you a twin.",
            ["last_merchant/relic"]="His finest piece. His last sale.",
            ["last_merchant/card"]="Rare cards from a closing shop.",
            ["last_merchant/shard"]="The last shards he'll ever sell.",
            ["dead_wanderer/technique"]="They'd want someone to carry it on.",
            ["dead_wanderer/fortune"]="They won't need the gold.",
            ["dead_wanderer/case"]="Two shards, still humming.",
            ["forbidden_vault/blood"]="It drinks before it opens.",
            ["forbidden_vault/gold"]="It counts before it opens.",
            ["forbidden_vault/curse"]="It marks you before it opens.",
            ["broken_hour/take"]="Steal a moment from every fight.",
            ["unfinished_relic/complete"]="Finish it with a piece of your own.",
            ["unfinished_relic/break"]="The core holds two shards.",
            ["unfinished_relic/sell"]="Half a relic is still worth something.",
            ["three_graves/power"]="Dig where the sword is buried.",
            ["three_graves/knowledge"]="Dig where the book is buried.",
            ["three_graves/fortune"]="Dig where the coins are buried.",
            ["price_of_perfection/accept"]="Every basic card, perfected, for a price.",
            ["price_of_perfection/refuse"]="Refuse it, but leave something behind.",
            ["fractured_altar/fracture"]="Break it early and get paid for the damage.",
            ["binder/bind"]="She picks the strand; you pick the card.",
            ["lost_travelers/stories"]="Their stories come with techniques.",
            ["lost_travelers/supplies"]="They have a shard they'd rather trade.",
            ["lost_travelers/rest"]="Share their fire for the night.",
            ["gilded_fountain/drink"]="It tastes like warm honey and coins.",
            ["gilded_fountain/wash"]="The water lifts a stain from your deck.",
            ["gilded_fountain/collect"]="A drop of it hardens into a shard.",
            ["fortune_teller/fortune"]="She tells you what you'll find, then hands it over.",
            ["crossroads_of_fate/power"]="The road that makes you stronger.",
            ["crossroads_of_fate/fortune"]="The road paved with coins.",
            ["crossroads_of_fate/possibility"]="The road you haven't imagined yet.",
            // Hero-only additions to classic events.
            ["abandoned_forge/warforge"]="Only a Vanguard knows this forge's song.",
            ["living_ink/hexwrite"]="A Hexer can read what the ink is writing.",
        };

        private static void ApplyClassicFlavor(List<EventDefinition> events)
        {
            var lines=ClassicFlavorLines();
            foreach(var e in events)foreach(var c in e.choices)
                if(string.IsNullOrEmpty(c.flavor)&&lines.TryGetValue(e.id+"/"+c.id,out var line))c.flavor=line;
        }
    }
}
